package io.github.mimimishkin.jni.binding.producer

internal object Symbols {
    val annotationPackage = "io.github.mimimishkin.jni.binding.annotation".pkg()
    val JniActual = annotationPackage.classId("JniActual")
    val JniActuals = annotationPackage.classId("JniActuals")
    val JniOnLoad = annotationPackage.classId("JniOnLoad")
    val JniOnUnload = annotationPackage.classId("JniOnUnload")
    val WithJvmSignature = annotationPackage.classId("WithJvmSignature")
    val WithJvmType = annotationPackage.classId("WithJvmType")
    val CriticalNative = annotationPackage.classId("CriticalNative")
    val DalvikCriticalNative = "dalvik.annotation.optimization".pkg().classId("CriticalNative")

    val classNameArgument = "className".ident()
    val typeArgument = "type".ident()
    val parameterTypesArgument = "parameterTypes".ident()
    val returnTypeArgument = "returnType".ident()

    val cinteropPackage = "kotlinx.cinterop".pkg()
    val CPointer = cinteropPackage.classId("CPointer")
    val CPointerVarOf = cinteropPackage.classId("CPointerVarOf")
    val COpaquePointer = cinteropPackage.classId("COpaquePointer")
    val NativePlacement = cinteropPackage.classId("NativePlacement")
    val AutofreeScope = cinteropPackage.classId("AutofreeScope")
    val ArenaBase = cinteropPackage.classId("ArenaBase")
    val MemScope = cinteropPackage.classId("MemScope")
    val CValues = cinteropPackage.classId("CValues")
    val CValuesRef = cinteropPackage.classId("CValuesRef")
    val CArrayPointer = cinteropPackage.classId("CArrayPointer")
    val CPrimitiveVar = cinteropPackage.classId("CPrimitiveVar")
    val ByteVar = cinteropPackage.classId("ByteVar")
    val UByteVar = cinteropPackage.classId("UByteVar")
    val ShortVar = cinteropPackage.classId("ShortVar")
    val UShortVar = cinteropPackage.classId("UShortVar")
    val IntVar = cinteropPackage.classId("IntVar")
    val LongVar = cinteropPackage.classId("LongVar")
    val ULongVar = cinteropPackage.classId("ULongVar")
    val FloatVar = cinteropPackage.classId("FloatVar")
    val DoubleVar = cinteropPackage.classId("DoubleVar")
    val CFunction = cinteropPackage.classId("CFunction")
    val CName = "kotlin.native".pkg().classId("CName")

    val JNINativeInterface = "jni".pkg().classId("JNINativeInterface_")
    val JNIInvokeInterface = "jni".pkg().classId("JNIInvokeInterface_")
    // Android has no cinterop of the JDK headers behind `jni-binding`: it uses the declarations Kotlin/Native
    // ships as `platform.android`, and those name the same structs without the trailing underscore.
    val JNINativeInterfaceAndroid = "platform.android".pkg().classId("JNINativeInterface")
    val JNIInvokeInterfaceAndroid = "platform.android".pkg().classId("JNIInvokeInterface")
    val JObjectRaw = "jni".pkg().classId("_jobject")
    val JClassRaw = "jni".pkg().classId("_jclass")

    val bindingPackage = "io.github.mimimishkin.jni.binding".pkg()
    internal val bindingAccessorsPackage = "io.github.mimimishkin.jni.binding.accessors".pkg()
    val JObjectWrapped = bindingPackage.classId("_jobject")
    val JClassWrapped = bindingPackage.classId("_jclass")
    val JArrayWrapped = bindingPackage.classId("_jarray")
    val JStringWrapped = bindingPackage.classId("_jstring")
    val JavaVM = bindingPackage.classId("JavaVM")
    val JniEnv = bindingPackage.classId("JniEnv")
    val JClass = bindingPackage.classId("JClass")
    val JNINativeMethodRegistry = bindingPackage.classId("JNINativeMethodRegistry")
    val JRef = bindingPackage.classId("JRef")
    val ApplyChangesMode = bindingPackage.classId("ApplyChangesMode")
    val JPrimitiveArray = bindingPackage.classId("_jprimitiveArray")
    val JBooleanArrayClass = bindingPackage.classId("_jbooleanArray")
    val JByteArrayClass = bindingPackage.classId("_jbyteArray")
    val JCharArrayClass = bindingPackage.classId("_jcharArray")
    val JShortArrayClass = bindingPackage.classId("_jshortArray")
    val JIntArrayClass = bindingPackage.classId("_jintArray")
    val JLongArrayClass = bindingPackage.classId("_jlongArray")
    val JFloatArrayClass = bindingPackage.classId("_jfloatArray")
    val JDoubleArrayClass = bindingPackage.classId("_jdoubleArray")
    val JNINativeInterfaceWrapped = bindingPackage.classId("Raw_JniNativeInterface")
    val JNIInvokeInterfaceWrapped = bindingPackage.classId("Raw_JniInvokeInterface")

    val generatedPackage = "jni.binding.generated".pkg()
    val entryPointBinding = generatedPackage.callableId("entryPointJniBinding")
    val exitPointBinding = generatedPackage.callableId("exitPointJniBinding")
}