[versions]
# https://github.com/JetBrains/kotlin
kotlin = "2.4.20"

# https://github.com/gmazzo/gradle-buildconfig-plugin
buildConfig = "6.1.2"

# https://developer.android.com/studio/releases/gradle-plugin
agp = "9.4.1"

# https://github.com/google/auto/blob/main/service/README.md
autoService = "1.1.1"

# https://github.com/google/ksp
ksp = "2.3.12"

# https://github.com/ZacSweers/auto-service-ksp
autoServiceKsp = "1.2.0"

# https://plugins.gradle.org/plugin/com.gradle.plugin-publish
pluginPublish = "2.2.1"

# https://github.com/vanniktech/gradle-maven-publish-plugin
mavenPublish = "0.37.0"

# https://github.com/zacsweers/kotlin-compile-testing
kct = "0.14.0"

# https://github.com/kotlin/dokka
dokka = "2.2.0"

# https://github.com/kotlin/kotlinx.serialization
serialization = "1.11.0"

# https://github.com/palantir/gradle-jdks
gradleJdks = "0.82.0"

# https://github.com/palantir/gradle-utils
palantirPlatform = "0.29.0"

# https://commons.apache.org/proper/commons-compress/
commonsCompress = "1.28.0"

[libraries]
androidTools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePluginApi  = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-compiler", version.ref = "kotlin" }
kotlin-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-embeddable", version.ref = "kotlin" }
autoService-annotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "autoService" }
zacsweers-autoServiceKsp = { group = "dev.zacsweers.autoservice", name = "auto-service-ksp", version.ref = "autoServiceKsp" }
zacsweers-kctFork = { group = "dev.zacsweers.kctfork", name = "core", version.ref = "kct" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
palantir-gradle-jdks = { group = "com.palantir.gradle.jdks", name = "gradle-jdks", version.ref = "gradleJdks" }
palantir-gradle-jdks-setup-common = { group = "com.palantir.gradle.jdks", name = "gradle-jdks-setup-common", version.ref = "gradleJdks" }
palantir-platform = { group = "com.palantir.gradle.utils", name = "platform", version.ref = "palantirPlatform" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-powerAssert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
android-kmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }