package io.github.mimimishkin.jni.binding.producer.ir

import io.github.mimimishkin.jni.binding.producer.Symbols
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.declarations.IrFile
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.expressions.IrBlockBody
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.IrGetValue
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid

/**
 * IR merger of the per-fragment hook machinery generated by
 * [io.github.mimimishkin.jni.binding.producer.fir.FirJniBindingGenerator].
 *
 * Only the platform fragment declares the `@CName` `JNI_OnLoad`/`JNI_OnUnload` entry points (empty shells);
 * Every fragment - contributes one *hook step* function per statement it must run.
 * This extension moves each on-load step's body into `JNI_OnLoad` and each on-unload step's body into `JNI_OnUnload`
 * and removes the step functions completely.
 */
@OptIn(UnsafeDuringIrConstructionAPI::class)
internal class JniHookStepsMerger : IrGenerationExtension {

    private companion object {
        /**
         * Step-name pattern `entryPointStep<phase>_<index><Load|Unload>`.
         * Phase and index drive the merge order.
         */
        val STEP_NAME = Regex("entryPointStep(\\d+)_(\\d+)(Load|Unload)")
    }

    /**
     * Extracts the generated entry points and hook steps from the `jni.binding.generated` package and
     * performs the merge described in the class doc. Does nothing when the fragment contains no
     * generated functions.
     */
    override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        val generatedFunctions = moduleFragment.files
            .filter { it.packageFqName == Symbols.generatedPackage }
            .flatMap { it.declarations.filterIsInstance<IrSimpleFunction>() }
        if (generatedFunctions.isEmpty()) return

        val entryPoint = generatedFunctions.single { it.name == Symbols.entryPointBinding.callableName }
        val exitPoint = generatedFunctions.single { it.name == Symbols.exitPointBinding.callableName }
        val steps = generatedFunctions.filter { it.name.asString() matches STEP_NAME }
        mergeSteps(entryPoint, sortedSteps(steps, onLoad = true), onLoad = true)
        mergeSteps(exitPoint, sortedSteps(steps, onLoad = false), onLoad = false)
    }

    /**
     * The steps of one phase (on-load or on-unload), sorted by phase, then by per-fragment index.
     */
    private fun sortedSteps(steps: List<IrSimpleFunction>, onLoad: Boolean): List<IrSimpleFunction> {
        val suffix = if (onLoad) "Load" else "Unload"
        return steps
            .filter { it.name.asString().endsWith(suffix) }
            .sortedWith(compareBy({ stepKey(it).first }, { stepKey(it).second }))
    }

    /**
     * Returns (phase, index) pair of the step.
     */
    private fun stepKey(function: IrSimpleFunction): Pair<Int, Int> {
        val match = STEP_NAME.matchEntire(function.name.asString())
            ?: error("hook step '${function.name}' does not match pattern '${STEP_NAME.pattern}'")
        return match.groupValues[1].toInt() to match.groupValues[2].toInt()
    }

    /**
     * Moves each step's body into [target] and remove steps.
     */
    private fun mergeSteps(target: IrSimpleFunction, steps: List<IrSimpleFunction>, onLoad: Boolean) {
        val targetBody = target.body as? IrBlockBody ?: error("entry point '${target.name}' has no body")
        val targetVm = target.parameters.first()

        val statements = mutableListOf<IrStatement>()
        steps.forEach { step ->
            val stepBody = step.body as? IrBlockBody ?: error("hook step '${step.name}' has no body")
            val rewriter = VmRewriter(step.parameters.single(), targetVm)
            stepBody.statements.forEach { statement ->
                statements.add(statement.transform(rewriter, null) as IrStatement)
            }
            step.removeFromParent()
        }
        if (statements.isEmpty()) return

        if (onLoad) {
            targetBody.statements.addAll(0, statements) // insert at 0 because we already have return statement
        } else {
            targetBody.statements.addAll(statements)
        }
    }

    private fun IrSimpleFunction.removeFromParent() {
        (parent as IrFile).declarations.remove(this)
    }

    /** Rewrites reads of the step's `vm` parameter to the entry point's `vm` parameter. */
    private class VmRewriter(
        private val from: IrValueParameter,
        private val to: IrValueParameter,
    ) : IrElementTransformerVoid() {
        override fun visitGetValue(expression: IrGetValue): IrExpression {
            if (expression.symbol.owner === from) {
                expression.symbol = to.symbol
            }
            return expression
        }
    }
}